default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: magicbook_dev_24
  # database: magicbook_dev_23

test:
  <<: *default
  database: magicbook_test
