default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: magicbook_sourced21
  # database: magicbook_ordered

test:
  <<: *default
  database: magicbook_test
